# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=200)),
                ('clubLogoUrl', models.CharField(max_length=200)),
                ('clubDescription', models.TextField(max_length=400)),
                ('clubWebpageUrl', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='clubImagesUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='clubs.Club')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ClubNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(max_length=100)),
                ('noticeDate', models.DateField(auto_now_add=True, db_index=True)),
                ('eventImageUrl', models.CharField(max_length=200)),
                ('eventDescription', models.TextField(max_length=400)),
                ('eventVenue', models.CharField(max_length=100)),
                ('eventTime', models.CharField(max_length=100)),
                ('eventDate', models.DateField(blank=True, null=True)),
                ('googleFormUrl', models.CharField(blank=True, max_length=200)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club', verbose_name='club')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('memberPosition', models.CharField(max_length=100)),
                ('memberImageUrl', models.CharField(max_length=400)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberName', to='clubs.Club')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('memberName', 'memberPosition', 'memberImageUrl', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='clubimagesurl',
            unique_together=set([('url', 'order')]),
        ),
    ]
