# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubimagesurl',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubImageUrl', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='clubnotice',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='member',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='clubs.Club'),
        ),
    ]
